name: Run Playwright Tests

on:
  schedule:
    - cron: '0 3 * * *'  # Schedule to run daily at 3 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for your tests

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install required libraries
        run: |
           sudo apt update
           sudo add-apt-repository universe  # Add the universe repository
           sudo apt update

           sudo apt install -y \
            libwoff2 libvpx7 libevent-2.1-7 libopus0 \
            libgstallocators* libgstapp* libgstpbutils* \
            libgstaudio* libgstgl* libgsttag* libgstvideo* \
            libgstcodecparsers* libgstfft* libharfbuzz-icu0 libhyphen0 \
            libflite1 libgles2 libx264 xvfb

      # Step 3: Set up JDK 21 with Maven cache
      - name: Set up JDK 21 and Maven cache
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # This is the default distribution for setup-java
          cache: 'maven'  # Optional caching for Maven dependencies

      # Step 4: Navigate to the project directory and run tests
      - name: Install dependencies and run tests
        run: |
          cd CometElite  # Navigate to the directory containing the pom.xml
          xvfb-run mvn clean test  # Run tests with xvfb
