name: Run Playwright Tests

on:
  schedule:
    - cron: '0 3 * * *'  # Schedule to run daily at 3 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for your tests

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21 with Maven cache
      - name: Set up JDK 21 and Maven cache
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # This is the default distribution for setup-java
          cache: 'maven'  # Optional caching for Maven dependencies

      # Step 3: Navigate to the project directory, install dependencies, and run tests
      - name: Install dependencies and run tests
        run: |
          cd CometElite  # Navigate to the directory containing the pom.xml
          mvn clean test
